/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<e5ed84377f21774081b2105b849f4927>>
 *
 * Generated by CLDRGenScript
 *
 *      
 */
const IntlVariations = require('IntlVariations');
const IntlCLDRNumberType42 = {
  getVariation(n        )         {
    return IntlVariations.NUMBER_OTHER;
  }
};

module.exports = IntlCLDRNumberType42;
