/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<c2851035cdca2e1835979327ada785ab>>
 *
 * Generated by CLDRGenScript
 *
 *      
 */
const IntlVariations = require('IntlVariations');
const IntlCLDRNumberType01 = {
  getVariation(n        )         {
    return IntlVariations.NUMBER_OTHER;
  }
};

module.exports = IntlCLDRNumberType01;
